version = 2
final_space = true
console_title_template =  '{{ .Shell }} in {{ .Folder }}'

[palette]
  os = "#ACB0BE"
  pink = "#F5C2E7"
  lavender = "#B4BEFE"
  blue =  "#89B4FA"

[transient_prompt]
  background = 'transparent'
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}p:blue{{end}}" 
  ]
  template = '❯ '

[secondary_prompt]
  background = 'transparent'
  foreground = 'p:blue'
  template = '❯❯ '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:pink'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:lavender"
    template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}{{ end }}{{ if gt .Ahead 0 }}{{ end }}"

    [blocks.segments.properties]
      branch_icon = "\ue725 "
      cherry_pick_icon = "\ue29b "
      commit_icon = "\uf417 "
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = "\ue727 "
      no_commits_icon = "\uf0c3 "
      rebase_icon = "\ue728 "
      revert_icon = "\uf0e2 "
      tag_icon = "\uf412 "

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    stype = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:blue{{end}}" 
    ]
    template = '❯'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.roperties]
      threshold = 5000

